<?php
/**
 * @file
 *
 * Module file containing HMS Commerce hooks.
 */

use Drupal\hms_commerce\PremiumContentManager;

/**
 * Implements hook_library_info_build.
 *
 * Adds libraries dynamically depending on module settings.
 */
function hms_commerce_library_info_build() {
  $libraries = [];
  $settings = \Drupal::service('hms_commerce.settings');

  // Add digtap widget js.
  $widget_js = $settings->getResourceUrl('digtap_widgets');
  if (!empty($widget_js)) {
    $libraries['products']['js'][$widget_js] = [
      'type' => 'external', 'minified' => TRUE];
  }

  // Add premium content js.
  $premium_content_js = $settings->getResourceUrl('premium_content');
  if (!empty($premium_content_js)) {
    $libraries['premiumContent']['js'][$premium_content_js] = [
      'type' => 'external', 'minified' => TRUE];
  }
  return $libraries;
}

/**
 * Implements hook_entity_view_alter.
 */
function hms_commerce_entity_view_alter(array &$build, Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {

  $manager = new PremiumContentManager($entity);
  if ($manager->isPremium()) {
    $manager->setEntitlementGroupName(\Drupal::service('hms_commerce.settings')->getSetting('entitlement_group_name'));
    $manager->encryptPremiumFields($build, \Drupal::service('hms_commerce.encrypter'));
    $manager->showTeaser($build);
  }
}
