<?php
/**
 * @file
 *
 * Module file containing HMS Commerce hooks.
 */

/**
 * Implements hook_library_info_build.
 *
 * Adds a JS library with dynamic source according to module settings.
 */
function hms_commerce_library_info_build() {
  $libraries = [];
  $widget_url = \Drupal::service('hms_commerce.settings')->getApiUrl('digtap_widgets');
  if (!empty($widget_url)) {
    $libraries['products']['js'][$widget_url] = [
      'type' => 'external', 'minified' => TRUE];
  }
  return $libraries;
}
